wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723461409
    t:
      1:
      - 1
      - 47
      - 53
      - 55
      2:
      - 1
      - 47
      - 53
      - 55
      3:
      - 23
      4: 3.9.10
      5: 0.17.6
      8:
      - 4
      - 5
      13: darwin-arm64
